#!/usr/bin/ruby

cmd = ARGV[0]

if ARGV.size == 0
  puts "Usage: ./theme [CMD] [options]"
  exit
elsif !File.exists?("bin/#{cmd}")
  puts "Command not found: #{cmd}"
  exit
else
  system("./bin/#{cmd} #{ARGV[1..-1].join(' ')}")
end
